import {
  Mic,
  MicOff,
  Video,
  VideoOff,
  Monitor,
  Hand,
  PhoneOff,
  MessageSquare,
  Users,
  BookOpen,
  FileText,
  Calendar,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Search,
  Settings,
  Bell,
  User,
  LogOut,
  Download,
  Circle,
  Plus,
  Pause,
  Play,
  Trash2,
  Send,
  Loader2,
  UserPlus,
  UserMinus
} from 'lucide-react';

export const Icons = {
  microphone: Mic,
  microphoneOff: MicOff,
  video: Video,
  videoOff: VideoOff,
  screenShare: Monitor,
  hand: Hand,
  phoneOff: PhoneOff,
  messageSquare: MessageSquare,
  users: Users,
  bookOpen: BookOpen,
  fileText: FileText,
  calendar: Calendar,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  info: Info,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  search: Search,
  settings: Settings,
  bell: Bell,
  user: User,
  logOut: LogOut,
  download: Download,
  record: Circle,
  plus: Plus,
  pause: Pause,
  play: Play,
  trash: Trash2,
  send: Send,
  spinner: Loader2,
  userPlus: UserPlus,
  userMinus: UserMinus
}; 